export type SafeParseResult<T>={success:true;data:T}|{success:false;error:SchemaError}
export class SchemaError extends TypeError { constructor(message:string,readonly path:readonly PropertyKey[]=[]){super(path.length?`${path.join('.')}: ${message}`:message);this.name='SchemaError'} }
export class Schema<T>{constructor(private validator:(value:unknown,path:PropertyKey[])=>T){}parse(value:unknown):T{return this.validator(value,[])}safeParse(value:unknown):SafeParseResult<T>{try{return{success:true,data:this.parse(value)}}catch(error){return{success:false,error:error instanceof SchemaError?error:new SchemaError(String(error))}}}optional():Schema<T|undefined>{return new Schema((value,path)=>value===undefined?undefined:this.validator(value,path))}refine(check:(value:T)=>boolean,message='Refinement failed'):Schema<T>{return new Schema((value,path)=>{const parsed=this.validator(value,path);if(!check(parsed))throw new SchemaError(message,path);return parsed})}}
export type InferSchema<S>=S extends Schema<infer T>?T:never
export const stringSchema=()=>new Schema<string>((value,path)=>{if(typeof value!=='string')throw new SchemaError('Expected string',path);return value})
export const numberSchema=()=>new Schema<number>((value,path)=>{if(typeof value!=='number'||Number.isNaN(value))throw new SchemaError('Expected number',path);return value})
export const booleanSchema=()=>new Schema<boolean>((value,path)=>{if(typeof value!=='boolean')throw new SchemaError('Expected boolean',path);return value})
export const literalSchema=<T extends string|number|boolean|null>(expected:T)=>new Schema<T>((value,path)=>{if(value!==expected)throw new SchemaError(`Expected ${String(expected)}`,path);return expected})
export const arraySchema=<T>(item:Schema<T>)=>new Schema<T[]>((value,path)=>{if(!Array.isArray(value))throw new SchemaError('Expected array',path);return value.map((entry,index)=>{try{return item.parse(entry)}catch(error){if(error instanceof SchemaError)throw new SchemaError(error.message,[...path,index,...error.path]);throw error}})})
export function objectSchema<S extends Record<string,Schema<any>>>(shape:S):Schema<{[K in keyof S]:InferSchema<S[K]>}>{return new Schema((value,path)=>{if(value===null||typeof value!=='object'||Array.isArray(value))throw new SchemaError('Expected object',path);const result:any={};for(const key of Object.keys(shape)){try{result[key]=shape[key].parse((value as any)[key])}catch(error){if(error instanceof SchemaError)throw new SchemaError(error.message,[...path,key,...error.path]);throw error}}return result})}
export function unionSchema<S extends readonly Schema<any>[]>(schemas:S):Schema<InferSchema<S[number]>>{return new Schema((value,path)=>{for(const schema of schemas){const result=schema.safeParse(value);if(result.success)return result.data}throw new SchemaError('No union variant matched',path)})}
